(function(){
  'use strict';
  var API='https://pipeline.studiozippy25.workers.dev/proxy/google-maps';
  var STORE='zippy_location_scout_v1';
  var state={initialized:false,results:[],selected:null,view:'satellite',meta:null,cards:[],previewTimer:null,roadHistory:[]};

  function $(id){return document.getElementById(id)}
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]})}
  function finite(value,fallback){var n=Number(value);return Number.isFinite(n)?n:fallback}
  function status(message,error){var el=$('lsStatus');if(!el)return;el.textContent=message||'';el.className='ls-status'+(message?' show':'')+(error?' error':'')}
  function loadCards(){try{var raw=JSON.parse(localStorage.getItem(STORE)||'[]');state.cards=Array.isArray(raw)?raw.filter(validPlace).slice(0,60):[]}catch(e){state.cards=[]}}
  function saveCards(){try{localStorage.setItem(STORE,JSON.stringify(state.cards.slice(0,60)))}catch(e){status('장소 카드 저장 실패: '+(e.message||e),true)}}
  function validPlace(p){return !!(p&&p.name&&Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lng)))}
  function controls(){return {zoom:finite($('lsZoom')&&$('lsZoom').value,17),heading:finite($('lsHeading')&&$('lsHeading').value,0),pitch:finite($('lsPitch')&&$('lsPitch').value,0),fov:finite($('lsFov')&&$('lsFov').value,80)}}
  function params(place,view){var c=controls();var q=new URLSearchParams({lat:String(place.lat),lng:String(place.lng),size:'640x360'});if(view==='satellite')q.set('zoom',String(c.zoom));else{q.set('heading',String(c.heading));q.set('pitch',String(c.pitch));q.set('fov',String(c.fov));if(place.panoId)q.set('pano',place.panoId)}return q}
  function previewUrl(place,view){return API+'/'+(view==='satellite'?'static':'streetview')+'?'+params(place,view)}
  function mapUrl(place){return place.googleMapsUri||('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(place.lat+','+place.lng))}
  function streetViewUrl(place){var c=controls();var q=new URLSearchParams({api:'1',map_action:'pano',viewpoint:place.lat+','+place.lng,heading:String(c.heading),pitch:String(c.pitch),fov:String(Math.min(100,c.fov))});var pano=place.panoId||(state.meta&&state.meta.pano_id);if(pano)q.set('pano',pano);return 'https://www.google.com/maps/@?'+q}
  function destination(lat,lng,bearing,distance){var radius=6378137,angular=distance/radius,heading=bearing*Math.PI/180,lat1=lat*Math.PI/180,lng1=lng*Math.PI/180;var lat2=Math.asin(Math.sin(lat1)*Math.cos(angular)+Math.cos(lat1)*Math.sin(angular)*Math.cos(heading));var lng2=lng1+Math.atan2(Math.sin(heading)*Math.sin(angular)*Math.cos(lat1),Math.cos(angular)-Math.sin(lat1)*Math.sin(lat2));return {lat:lat2*180/Math.PI,lng:((lng2*180/Math.PI+540)%360)-180}}

  async function api(path,options){
    var response=await fetch(API+path,Object.assign({headers:{Accept:'application/json'}},options||{}));
    var type=response.headers.get('content-type')||'';var data=type.indexOf('json')>=0?await response.json():{error:await response.text()};
    if(!response.ok)throw new Error(data.error||data.message||('HTTP '+response.status));return data;
  }
  async function checkHealth(){
    var el=$('lsHealth');if(!el)return;
    try{var data=await api('/health');var ok=!!data.configured;el.className='ls-health '+(ok?'ok':'bad');el.innerHTML='<span></span>'+(ok?'Google Maps 연결됨':'지도 키 설정 필요');}
    catch(e){el.className='ls-health bad';el.innerHTML='<span></span>프록시 연결 실패';}
  }
  function renderShotOptions(){var sel=$('lsShotSelect');if(!sel)return;var old=sel.value;var shots=(typeof SB_SHOTS!=='undefined'&&Array.isArray(SB_SHOTS))?SB_SHOTS:[];sel.innerHTML='<option value="">스토리보드 쇼트 선택</option>'+shots.map(function(s){return '<option value="'+esc(s.id)+'">'+esc(s.id+' · '+(s.frame||s.desc||''))+'</option>'}).join('');if(shots.some(function(s){return s.id===old}))sel.value=old}

  function renderResults(){var wrap=$('lsResults'),count=$('lsResultCount');if(!wrap)return;if(count)count.textContent=state.results.length?state.results.length+'곳':'결과 없음';wrap.innerHTML=state.results.length?state.results.map(function(p,i){var on=state.selected&&String(state.selected.id)===String(p.id);return '<button type="button" class="ls-result'+(on?' on':'')+'" onclick="locationScoutSelect('+i+')"><b>'+esc(p.name)+'</b><span>'+esc(p.address||'주소 정보 없음')+'</span><small>'+finite(p.lat,0).toFixed(5)+' · '+finite(p.lng,0).toFixed(5)+'</small></button>'}).join(''):'<div class="ls-empty">일치하는 장소가 없습니다. 더 넓은 지역명이나 다른 키워드로 검색해보세요.</div>'}
  function renderSelected(){
    var p=state.selected;if(!p)return;
    $('lsSelectedName').textContent=p.name;$('lsSelectedAddress').textContent=p.address||'주소 정보 없음';
    $('lsSatelliteTab').classList.toggle('on',state.view==='satellite');$('lsStreetTab').classList.toggle('on',state.view==='streetview');
    $('lsRoadNav').hidden=state.view!=='streetview';$('lsBackBtn').disabled=!state.roadHistory.length;
    $('lsZoomControl').hidden=state.view!=='satellite';$('lsHeadingControl').hidden=state.view!=='streetview';$('lsPitchControl').hidden=state.view!=='streetview';$('lsFovControl').hidden=state.view!=='streetview';
    $('lsZoomOut').value=controls().zoom;$('lsHeadingOut').value=controls().heading+'°';$('lsPitchOut').value=controls().pitch+'°';$('lsFovOut').value=controls().fov+'°';
    var metaStatus=state.meta&&state.meta.status==='OK'?((state.meta.date?state.meta.date+' · ':'')+(state.meta.copyright||'사용 가능')):(state.meta&&state.meta.status?state.meta.status:'확인 중');
    $('lsMeta').innerHTML='<span>좌표 '+finite(p.lat,0).toFixed(6)+', '+finite(p.lng,0).toFixed(6)+'</span><span>스트리트뷰 '+esc(metaStatus)+'</span>';
    renderPreview();renderResults();
  }
  function renderPreview(){var p=state.selected,wrap=$('lsPreview');if(!p||!wrap)return;wrap.classList.add('loading');var img=new Image();img.alt=p.name+' '+(state.view==='satellite'?'위성':'스트리트뷰')+' 프리뷰';img.onload=function(){wrap.classList.remove('loading')};img.onerror=function(){wrap.classList.remove('loading');wrap.innerHTML='<div class="ls-preview-empty"><span>!</span><b>프리뷰를 불러오지 못했습니다.</b><small>API 활성화와 결제 설정을 확인하세요.</small></div>'};img.src=previewUrl(p,state.view);wrap.replaceChildren(img)}
  async function loadStreetMeta(){var p=state.selected;if(!p)return;state.meta=null;try{state.meta=await api('/streetview/metadata?'+new URLSearchParams({lat:String(p.lat),lng:String(p.lng)}));if(state.meta&&state.meta.pano_id&&state.selected===p)state.selected.panoId=state.meta.pano_id;}catch(e){state.meta={status:'확인 실패'}}if(state.selected===p)renderSelected()}

  window.locationScoutInit=function(){if(!state.initialized){state.initialized=true;loadCards();renderCards()}checkHealth();renderShotOptions()};
  window.locationScoutSearch=async function(event){if(event)event.preventDefault();var q=($('lsQuery').value||'').trim();if(q.length<2){status('두 글자 이상 검색어를 입력하세요.',true);return}var btn=$('lsSearchBtn');btn.disabled=true;btn.textContent='검색 중…';status('Google Places에서 장소 후보를 찾는 중입니다.');try{var data=await api('/search',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({query:q,languageCode:'ko',regionCode:'KR'})});state.results=(data.places||[]).filter(validPlace);state.selected=null;state.meta=null;renderResults();if(state.results.length)window.locationScoutSelect(0);status(state.results.length+'개의 장소 후보를 찾았습니다.');}catch(e){state.results=[];renderResults();status('장소 검색 실패: '+(e.message||e),true)}finally{btn.disabled=false;btn.textContent='장소 검색'}};
  window.locationScoutQuickSearch=function(q){$('lsQuery').value=q;window.locationScoutSearch()};
  window.locationScoutSelect=function(index){var p=state.results[index];if(!p)return;state.selected=Object.assign({},p);state.meta=null;state.roadHistory=[];renderSelected();loadStreetMeta()};
  window.locationScoutSetView=function(view){if(view!=='satellite'&&view!=='streetview')return;state.view=view;renderSelected()};
  window.locationScoutControlChanged=function(){var c=controls();$('lsZoomOut').value=c.zoom;$('lsHeadingOut').value=c.heading+'°';$('lsPitchOut').value=c.pitch+'°';$('lsFovOut').value=c.fov+'°';clearTimeout(state.previewTimer);state.previewTimer=setTimeout(renderPreview,180)};
  window.locationScoutOpenMaps=function(){if(!state.selected){status('먼저 장소를 선택하세요.',true);return}window.open(state.view==='streetview'?streetViewUrl(state.selected):mapUrl(state.selected),'_blank','noopener,noreferrer')};
  window.locationScoutRotate=function(delta){if(!state.selected)return;var heading=(controls().heading+delta+360)%360;$('lsHeading').value=heading;window.locationScoutControlChanged()};
  window.locationScoutMoveForward=async function(){if(!state.selected||state.view!=='streetview'){status('STREET VIEW에서 장소를 선택하세요.',true);return}var button=$('lsForwardBtn'),current=Object.assign({},state.selected),currentMeta=state.meta?Object.assign({},state.meta):null,bearing=controls().heading;button.disabled=true;button.textContent='도로 탐색 중…';status('진행 방향의 다음 스트리트뷰 파노라마를 찾는 중입니다.');try{var found=null;for(var distance of [18,35,60]){var point=destination(current.lat,current.lng,bearing,distance);var meta=await api('/streetview/metadata?'+new URLSearchParams({lat:String(point.lat),lng:String(point.lng)}));if(meta.status==='OK'&&meta.location&&meta.pano_id&&meta.pano_id!==(current.panoId||(currentMeta&&currentMeta.pano_id))){found=meta;break}}if(!found){status('이 방향에서 다음 파노라마를 찾지 못했습니다. 방향을 조금 돌린 뒤 다시 시도하세요.',true);return}state.roadHistory.push({selected:current,meta:currentMeta});state.selected=Object.assign({},current,{lat:Number(found.location.lat),lng:Number(found.location.lng),panoId:found.pano_id});state.meta=found;renderSelected();status('앞쪽 도로의 다음 파노라마로 이동했습니다.');}catch(e){status('앞으로 이동 실패: '+(e.message||e),true)}finally{button.disabled=false;button.textContent='↑ 앞으로 이동'}};
  window.locationScoutGoBack=function(){var previous=state.roadHistory.pop();if(!previous)return;state.selected=previous.selected;state.meta=previous.meta;renderSelected();status('이전 스트리트뷰 위치로 돌아왔습니다.')};
  window.locationScoutSaveCard=function(){if(!state.selected){status('먼저 장소를 선택하세요.',true);return}var c=controls(),p=state.selected;var card={id:'loc_'+Date.now(),placeId:p.id||'',name:p.name,address:p.address||'',lat:Number(p.lat),lng:Number(p.lng),googleMapsUri:mapUrl(p),view:state.view,zoom:c.zoom,heading:c.heading,pitch:c.pitch,fov:c.fov,streetViewStatus:state.meta&&state.meta.status||'',streetViewDate:state.meta&&state.meta.date||'',savedAt:new Date().toISOString()};state.cards.unshift(card);saveCards();renderCards();status('“'+p.name+'” 장소 카드를 저장했습니다. 이미지가 아닌 메타데이터만 저장됩니다.')};
  window.locationScoutUseCard=function(id){var card=state.cards.find(function(x){return x.id===id});if(!card)return;state.selected=Object.assign({},card,{id:card.placeId||card.id});state.view=card.view||'satellite';$('lsZoom').value=card.zoom||17;$('lsHeading').value=card.heading||0;$('lsPitch').value=card.pitch||0;$('lsFov').value=card.fov||80;state.meta={status:card.streetViewStatus||'',date:card.streetViewDate||''};renderSelected();window.scrollTo({top:$('pScout').offsetTop-20,behavior:'smooth'});loadStreetMeta()};
  window.locationScoutDeleteCard=function(id){state.cards=state.cards.filter(function(x){return x.id!==id});saveCards();renderCards();status('장소 카드를 삭제했습니다.')};
  window.locationScoutClearCards=function(){if(!state.cards.length)return;if(!confirm('저장된 장소 카드 메타데이터를 모두 지울까요?'))return;state.cards=[];saveCards();renderCards();status('저장된 장소 카드를 모두 비웠습니다.')};
  function renderCards(){var wrap=$('lsSavedCards');if(!wrap)return;wrap.innerHTML=state.cards.length?state.cards.map(function(c){return '<article class="ls-card"><div class="ls-card-preview"><img loading="lazy" src="'+esc(previewUrl(c,c.view||'satellite'))+'" alt="'+esc(c.name)+' 프리뷰"></div><div class="ls-card-body"><b>'+esc(c.name)+'</b><p>'+esc(c.address||'주소 정보 없음')+'</p><div class="ls-card-tags"><span>'+esc((c.view||'satellite').toUpperCase())+'</span><span>'+finite(c.lat,0).toFixed(5)+', '+finite(c.lng,0).toFixed(5)+'</span></div><div class="ls-card-actions"><button onclick="locationScoutUseCard(\''+esc(c.id)+'\')">불러오기</button><button onclick="locationScoutOpenSavedMap(\''+esc(c.id)+'\')">지도 ↗</button><button class="danger" onclick="locationScoutDeleteCard(\''+esc(c.id)+'\')">삭제</button></div></div></article>'}).join(''):'<div class="ls-empty">저장한 장소 카드가 없습니다.</div>'}
  window.locationScoutOpenSavedMap=function(id){var card=state.cards.find(function(x){return x.id===id});if(card)window.open(mapUrl(card),'_blank','noopener,noreferrer')};
  function brief(p){var c=controls();return ['LOCATION SCOUT REFERENCE',p.name,p.address||'', 'Coordinates: '+p.lat+', '+p.lng,'View: '+state.view+(state.view==='satellite'?' / zoom '+c.zoom:' / heading '+c.heading+' / pitch '+c.pitch+' / fov '+c.fov),(state.meta&&state.meta.date?'Street View date: '+state.meta.date:''),'Google Maps: '+mapUrl(p)].filter(Boolean).join('\n')}
  window.locationScoutCopyBrief=async function(){if(!state.selected){status('먼저 장소를 선택하세요.',true);return}try{await navigator.clipboard.writeText(brief(state.selected));status('장소 브리프를 클립보드에 복사했습니다.')}catch(e){status('클립보드 복사 실패: '+(e.message||e),true)}};
  window.locationScoutSendToShot=function(){if(!state.selected){status('먼저 장소를 선택하세요.',true);return}var shotId=$('lsShotSelect').value;if(!shotId){status('연결할 스토리보드 쇼트를 선택하세요.',true);return}if(typeof SB_SHOTS==='undefined'){status('스토리보드 데이터를 불러오지 못했습니다.',true);return}var shot=SB_SHOTS.find(function(s){return s.id===shotId});if(!shot){status('선택한 쇼트를 찾지 못했습니다.',true);return}var p=state.selected;shot.loc='[GOOGLE PLACE] '+p.name+(p.address?' · '+p.address:'')+' · '+Number(p.lat).toFixed(6)+','+Number(p.lng).toFixed(6);shot.locationScout={name:p.name,address:p.address||'',lat:Number(p.lat),lng:Number(p.lng),googleMapsUri:mapUrl(p)};if(typeof saveStoryboardState==='function')saveStoryboardState('location-scout');if(typeof buildStoryboardTimeline==='function')buildStoryboardTimeline();status(shotId+'의 장소를 “'+p.name+'”로 연결했습니다.');};
})();
