(function(){
  'use strict';

  const SOURCE={title:'Reactor Prompts Magazine',url:'https://reactorprompt.vercel.app/templates',author:'Reactor / simartkrom',license:'Public reuse license confirmed by source provider',extracted:'2026-08-20'};
  const TEMPLATES=[
    {id:'portrait-basic',title:'기본 인물 포트레이트',description:'자연스러운 인물 사진을 위한 기본 구조. 주체, 의상, 배경, 조명 순서로 구성합니다.',template:'{SHOT_TYPE} portrait of a {AGE}-year-old {NATIONALITY} woman with {HAIR_DESCRIPTION}, wearing {OUTFIT_DESCRIPTION}. {BACKGROUND_DESCRIPTION}. {LIGHTING_DESCRIPTION}, {MOOD_KEYWORDS}.',variables:['SHOT_TYPE','AGE','NATIONALITY','HAIR_DESCRIPTION','OUTFIT_DESCRIPTION','BACKGROUND_DESCRIPTION','LIGHTING_DESCRIPTION','MOOD_KEYWORDS'],example:'Close-up portrait of a 22-year-old Korean woman with long wavy dark-brown hair, wearing a cream knit sweater. Warm modern café with wooden decor softly blurred behind her. Soft golden hour lighting, warm tones, editorial mood.',category:'portrait',difficulty:'beginner'},
    {id:'portrait-fashion-editorial',title:'패션 에디토리얼',description:'하이엔드 패션 매거진 스타일의 프롬프트. 의상 디테일과 포즈를 강조합니다.',template:'Professional fashion magazine {SHOT_TYPE} of a {SUBJECT_DESCRIPTION}. She wears {DETAILED_OUTFIT}. {POSE_DESCRIPTION}. {BACKGROUND}. Shot with {CAMERA_STYLE}, {LIGHTING}, {COLOR_GRADE}.',variables:['SHOT_TYPE','SUBJECT_DESCRIPTION','DETAILED_OUTFIT','POSE_DESCRIPTION','BACKGROUND','CAMERA_STYLE','LIGHTING','COLOR_GRADE'],example:'Professional fashion magazine editorial of a young woman with striking burgundy red hair and choppy bangs. She wears a crisp white collared shirt under a structured oversized blazer. Arms crossed elegantly. Minimalist studio with soft gray backdrop. Shot with 85mm lens shallow DOF, diffused natural window light, desaturated cool tones.',category:'portrait',difficulty:'intermediate'},
    {id:'portrait-beauty-closeup',title:'뷰티 클로즈업',description:'피부 질감과 메이크업 디테일을 강조하는 극접사 뷰티 샷.',template:'extreme close-up {NATIONALITY} woman face {FRAMING_ELEMENT}, {PHOTOGRAPHY_STYLE} perfect skin texture, {LIGHTING_STYLE}, {CONCEPT_DESCRIPTION}, natural modern {MOOD}.',variables:['NATIONALITY','FRAMING_ELEMENT','PHOTOGRAPHY_STYLE','LIGHTING_STYLE','CONCEPT_DESCRIPTION','MOOD'],example:'extreme close-up Korean woman face framed by giant white butterfly wings, macro photography perfect skin texture, soft lighting through translucent wings, transformation beauty concept, natural modern elegance.',category:'portrait',difficulty:'intermediate'},
    {id:'cosplay-portrait',title:'코스프레 포트레이트',description:'캐릭터 의상과 스타일링을 상세하게 묘사하는 코스프레 전용 구조.',template:'Cosplay portrait of a young woman styled as {CHARACTER_CONCEPT}, with {HAIR_STYLE}, {FACIAL_FEATURES}. She wears {COSTUME_DETAILS}. {POSE_AND_PROPS}. {BACKGROUND_SETTING}. {LIGHTING_AND_MOOD}.',variables:['CHARACTER_CONCEPT','HAIR_STYLE','FACIAL_FEATURES','COSTUME_DETAILS','POSE_AND_PROPS','BACKGROUND_SETTING','LIGHTING_AND_MOOD'],example:'Cosplay portrait of a young woman styled as a celestial fantasy elf, with long wavy ice-blue hair, glowing blue eyes, translucent blue horns, and pointed elf ears. She wears a sleeveless dark navy dress with silver embroidery. Holding a glowing crystal orb. Ancient forest ruins with floating particles. Ethereal moonlight, mystical atmosphere.',category:'cosplay',difficulty:'intermediate'},
    {id:'cosplay-multi-panel',title:'멀티 패널 코스프레',description:'여러 앵글이나 의상 변화를 한 이미지에 담는 패널 구성.',template:'Four-panel {THEME} cosplay {SHOT_TYPE} of a {SUBJECT}. Panel layout: {PANEL_1} | {PANEL_2} | {PANEL_3} | {PANEL_4}. Consistent {STYLE_CONSISTENCY}. {OVERALL_MOOD}.',variables:['THEME','SHOT_TYPE','SUBJECT','PANEL_1','PANEL_2','PANEL_3','PANEL_4','STYLE_CONSISTENCY','OVERALL_MOOD'],example:'Four-panel athleisure cosplay editorial of a young Korean woman. Panel layout: front pose in sporty crop top | side profile stretching | back view walking away | close-up face with headband. Consistent soft natural lighting and warm gym interior. Energetic yet elegant mood.',category:'cosplay',difficulty:'advanced',allowPanel:true},
    {id:'food-dessert',title:'디저트/음식 촬영',description:'고급 음식 사진을 위한 구조. 질감, 조명, 스타일링을 강조합니다.',template:'Photorealistic editorial food photography of {FOOD_ITEM}. {PLATING_DESCRIPTION}. {GARNISH_AND_PROPS}. {SURFACE_AND_BACKGROUND}. {LIGHTING_SETUP}. {MOOD_AND_STYLE}.',variables:['FOOD_ITEM','PLATING_DESCRIPTION','GARNISH_AND_PROPS','SURFACE_AND_BACKGROUND','LIGHTING_SETUP','MOOD_AND_STYLE'],example:'Photorealistic editorial food photography of a single matcha tiramisu slice. Layered cross-section showing green tea cream and ladyfinger layers. Dusted with matcha powder, gold leaf accent. Dark slate surface with scattered tea leaves. Moody side lighting with soft fill. Minimalistic luxury dessert magazine style.',category:'food',difficulty:'beginner'},
    {id:'product-beauty',title:'뷰티 제품 광고',description:'화장품/뷰티 제품을 손에 들고 있는 럭셔리 광고 스타일.',template:'Ultra-realistic luxury beauty ad shot of a {PRODUCT_TYPE} with {KEY_DESIGN_DETAILS}, held delicately between {HAND_DESCRIPTION}. The product floats slightly above {HAND_POSITION}, with {FINGER_ACTION}. {BACKGROUND_ELEMENTS}. {LIGHTING_DESCRIPTION}. {OVERALL_AESTHETIC}.',variables:['PRODUCT_TYPE','KEY_DESIGN_DETAILS','HAND_DESCRIPTION','HAND_POSITION','FINGER_ACTION','BACKGROUND_ELEMENTS','LIGHTING_DESCRIPTION','OVERALL_AESTHETIC'],example:'Ultra-realistic luxury beauty ad shot of a rose-gold lipstick tube with embossed floral pattern, held delicately between slender fingers with nude manicure. The product floats slightly above an open palm, with fingertips barely touching. Scattered rose petals and soft bokeh. Warm diffused studio lighting. High-end Chanel campaign aesthetic.',category:'food',difficulty:'advanced'},
    {id:'illustration-anime',title:'애니메이션/일러스트',description:'애니메이션 스타일 일러스트를 위한 프롬프트 구조.',template:'Anime {STYLE_REFERENCE} illustration of {CHARACTER_DESCRIPTION}. {ACTION_OR_POSE}. {ENVIRONMENT_DETAILS}. {ART_STYLE_KEYWORDS}, {COLOR_PALETTE}, {RENDERING_QUALITY}.',variables:['STYLE_REFERENCE','CHARACTER_DESCRIPTION','ACTION_OR_POSE','ENVIRONMENT_DETAILS','ART_STYLE_KEYWORDS','COLOR_PALETTE','RENDERING_QUALITY'],example:'Anime poster-style illustration of a young woman with flowing cherry-blossom pink hair in traditional hanbok. Standing on a moonlit bridge over a koi pond. Surrounded by floating lanterns and petals. Ghibli-inspired watercolor textures, warm golden and pink palette, highly detailed digital painting.',category:'illustration',difficulty:'beginner',allowIllustration:true},
    {id:'illustration-sticker',title:'스티커/포토부스',description:'귀여운 스티커 시트나 포토부스 컷 스타일 프롬프트.',template:'A {NUMBER}-cut sticker {FORMAT} featuring {SUBJECT_DESCRIPTION} in {NUMBER} different frames, each showing {VARIATION_DESCRIPTION}. The images feel {MOOD_DESCRIPTION}. {STYLE_DETAILS}. {BACKGROUND_STYLE}.',variables:['NUMBER','FORMAT','SUBJECT_DESCRIPTION','VARIATION_DESCRIPTION','MOOD_DESCRIPTION','STYLE_DETAILS','BACKGROUND_STYLE'],example:'A nine-cut sticker photo booth strip featuring a young beautiful woman in nine different frames, each showing a new outfit, pose, and expression. The images feel nostalgic and bittersweet, like cherished memories. Soft film grain, slightly faded colors. Clean white background with rounded corners.',category:'illustration',difficulty:'intermediate',allowPanel:true},
    {id:'technical-metadata',title:'카메라 메타데이터 스타일',description:'실제 카메라 설정값을 포함하여 사실적인 사진 느낌을 강화합니다.',template:'{SCENE_DESCRIPTION}. Shot on {CAMERA_MODEL} with {LENS_SPEC}, {APERTURE}, {SHUTTER_SPEED}, ISO {ISO_VALUE}. {POST_PROCESSING}. {FILM_STYLE}.',variables:['SCENE_DESCRIPTION','CAMERA_MODEL','LENS_SPEC','APERTURE','SHUTTER_SPEED','ISO_VALUE','POST_PROCESSING','FILM_STYLE'],example:'Candid street portrait of a young woman walking through autumn leaves in Bukchon Hanok Village. Shot on Sony A7IV with 85mm f/1.4 GM, f/1.8, 1/500s, ISO 200. Minimal post-processing, natural colors. Kodak Portra 400 film emulation.',category:'technical',difficulty:'intermediate'},
    {id:'technical-lighting',title:'조명 설정 가이드',description:'스튜디오 조명 설정을 상세하게 지정하는 프롬프트 패턴.',template:'{SUBJECT_DESCRIPTION}. Lighting setup: {KEY_LIGHT} as key light at {KEY_POSITION}, {FILL_LIGHT} as fill at {FILL_POSITION}, {RIM_LIGHT} as rim/hair light. {MODIFIER_DETAILS}. {RESULTING_MOOD}.',variables:['SUBJECT_DESCRIPTION','KEY_LIGHT','KEY_POSITION','FILL_LIGHT','FILL_POSITION','RIM_LIGHT','MODIFIER_DETAILS','RESULTING_MOOD'],example:'Beauty portrait of a model with glowing skin. Lighting setup: Large octabox as key light at 45° camera left, silver reflector as fill at camera right, strip softbox as rim/hair light. Diffusion panel between key and subject for extra softness. Resulting in creamy skin tones with subtle dimension.',category:'technical',difficulty:'advanced'},
    {id:'structure-layered',title:'레이어드 프롬프트 구조',description:'주제 → 디테일 → 환경 → 기술 → 무드 순서의 체계적 구조.',template:'[Subject] {MAIN_SUBJECT}\n[Details] {APPEARANCE_DETAILS}\n[Environment] {SETTING_DESCRIPTION}\n[Technical] {CAMERA_AND_LIGHTING}\n[Mood] {ATMOSPHERE_KEYWORDS}',variables:['MAIN_SUBJECT','APPEARANCE_DETAILS','SETTING_DESCRIPTION','CAMERA_AND_LIGHTING','ATMOSPHERE_KEYWORDS'],example:'[Subject] Young Korean woman, early 20s, natural beauty\n[Details] Long straight black hair, minimal makeup, white linen dress\n[Environment] Sunlit greenhouse with tropical plants\n[Technical] 50mm lens, f/2.0, golden hour backlight\n[Mood] Serene, ethereal, warm, dreamy',category:'structure',difficulty:'beginner'},
    {id:'structure-generator',title:'메타 프롬프트 (생성기)',description:'AI에게 프롬프트를 생성하도록 요청하는 메타 구조. 매번 다른 결과를 얻습니다.',template:'You are {ROLE_DESCRIPTION}. Each time this prompt is used, randomly create one complete English image prompt for {SUBJECT_DOMAIN}. Requirements: {REQUIREMENT_LIST}. Output only the image prompt, no explanation.',variables:['ROLE_DESCRIPTION','SUBJECT_DOMAIN','REQUIREMENT_LIST'],example:'You are a high-end food photography prompt generator. Each time this prompt is used, randomly create one complete English image prompt for a moody, minimalistic dessert or food photography composition. Requirements: vary the food type, plating style, surface material, lighting angle, and color mood each time. Output only the image prompt, no explanation.',category:'structure',difficulty:'advanced'},
    {id:'structure-infographic',title:'인포그래픽 템플릿',description:'교육용 인포그래픽 포스터를 위한 마스터 프롬프트 구조.',template:'[MASTER PROMPT TEMPLATE]\n{STYLE_REFERENCE} 감성의 {ORIENTATION}형 {TOPIC} 교육 인포그래픽 포스터를 제작한다.\n주제: "{TITLE}"\n구성: {LAYOUT_DESCRIPTION}\n디자인: {DESIGN_GUIDELINES}\n컬러: {COLOR_SCHEME}',variables:['STYLE_REFERENCE','ORIENTATION','TOPIC','TITLE','LAYOUT_DESCRIPTION','DESIGN_GUIDELINES','COLOR_SCHEME'],example:'[MASTER PROMPT TEMPLATE]\n고급 카메라 매거진과 Sony Alpha Academy 감성의 가로형 웨딩 사진 교육 인포그래픽 포스터를 제작한다.\n주제: "저장판 | 오늘의 웨딩사진 잘 찍는 방법 10선"\n구성: 상단 타이틀 + 10개 팁 그리드 + 하단 요약\n디자인: 미니멀, 여백 활용, 아이콘 포인트\n컬러: 다크 네이비 + 골드 악센트',category:'structure',difficulty:'advanced',allowText:true}
  ];
  const CATEGORIES=[['all','전체'],['portrait','인물/화보'],['food','음식/제품'],['illustration','일러스트'],['cosplay','코스프레'],['technical','촬영 기법'],['structure','구조/패턴']];
  let category='all',query='',builder=null,values={};

  function esc(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function jsq(v){return String(v||'').replace(/\\/g,'\\\\').replace(/'/g,"\\'");}
  function find(id){return TEMPLATES.find(function(t){return t.id===id;})||null;}
  function selectedFromPrompt(){const input=document.getElementById('ipCustomPrompt');if(!input)return null;const m=String(input.value||'').match(/^\[REACTOR STYLE: ([^\]|]+) \|/);return m?find(m[1].trim()):null;}
  function adaptation(t,prompt){
    let rule='Use the Reactor prompt above for composition, camera, lighting, rendering, and mood. Replace every described person, face, age, ethnicity, hairstyle, body, outfit, brand, and location with the uploaded approved Instagram identity, clothing-only outfit sheet, and selected place references. Identity reference 1 and the approved wardrobe sheet remain authoritative.';
    if(t.category==='food')rule+=' Stage the approved persona naturally interacting with or presenting the food/product unless the user explicitly requests a product-only composition.';
    if(t.allowIllustration)rule+=' Stylized illustration/anime rendering is explicitly allowed for this selected Reactor style, while recognizable identity markers and outfit silhouette remain consistent.';
    if(t.allowPanel)rule+=' The requested multi-panel or sticker layout is explicitly allowed for this selected Reactor style.';
    if(t.allowText)rule+=' Designed title and infographic text are explicitly allowed for this selected Reactor style; keep spelling exactly as supplied.';
    return '[REACTOR STYLE: '+t.id+' | '+t.title+']\n'+prompt+'\n\nSTUDIO ZIPPY ADAPTATION RULE:\n'+rule+'\nSOURCE CREDIT: Reactor Prompts Magazine · public licensed template.';
  }
  function apply(id,prompt){const t=find(id),input=document.getElementById('ipCustomPrompt');if(!t||!input)return;input.value=adaptation(t,prompt||t.example);input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));const selected=document.getElementById('reactorPromptSelected');if(selected){selected.className='reactor-selected show';selected.innerHTML='<b>'+esc(t.title)+'</b> 적용됨 · 업로드한 인물·의상·장소가 우선합니다. <button type="button" onclick="reactorClearPromptStyle()" style="margin-left:8px;border:0;background:transparent;color:#f472b6;cursor:pointer">해제</button>';}render();input.scrollIntoView({behavior:'smooth',block:'center'});}
  function clearSelection(){const input=document.getElementById('ipCustomPrompt');if(input&&/^\[REACTOR STYLE:/.test(input.value))input.value='';if(input){input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));}render();}
  function render(){const root=document.getElementById('reactorPromptLibrary');if(!root)return;const selected=selectedFromPrompt();const list=TEMPLATES.filter(function(t){const cat=category==='all'||t.category===category;const q=!query||[t.title,t.description,t.template,t.example].join(' ').toLowerCase().includes(query.toLowerCase());return cat&&q;});root.innerHTML='<div class="reactor-toolbar"><input id="reactorPromptSearch" class="reactor-search" type="search" placeholder="14개 스타일 검색" value="'+esc(query)+'" oninput="reactorSearchPrompts(this.value)">'+CATEGORIES.map(function(c){return'<button class="reactor-filter '+(category===c[0]?'on':'')+'" onclick="reactorFilterPrompts(\''+c[0]+'\')">'+c[1]+'</button>';}).join('')+'</div><div id="reactorPromptSelected" class="reactor-selected '+(selected?'show':'')+'">'+(selected?'<b>'+esc(selected.title)+'</b> 적용됨 · 업로드한 인물·의상·장소가 우선합니다. <button type="button" onclick="reactorClearPromptStyle()" style="margin-left:8px;border:0;background:transparent;color:#f472b6;cursor:pointer">해제</button>':'')+'</div><div class="reactor-grid">'+(list.length?list.map(function(t){return'<article class="reactor-card '+(selected&&selected.id===t.id?'selected':'')+'"><button class="reactor-title" onclick="reactorApplyPrompt(\''+jsq(t.id)+'\')">'+esc(t.title)+'</button><div class="reactor-meta"><span class="reactor-badge">'+esc(CATEGORIES.find(function(c){return c[0]===t.category;})?.[1]||t.category)+'</span><span class="reactor-badge">'+esc(t.difficulty)+'</span></div><div class="reactor-desc">'+esc(t.description)+'</div><pre class="reactor-template-preview">'+esc(t.template)+'</pre><div class="reactor-card-actions"><button class="reactor-apply" onclick="reactorApplyPrompt(\''+jsq(t.id)+'\')">스타일 적용</button><button class="reactor-build" onclick="reactorOpenBuilder(\''+jsq(t.id)+'\')">변수 편집</button></div></article>';}).join(''):'<div class="reactor-empty">검색 결과가 없습니다.</div>')+'</div><div class="reactor-credit" style="margin-top:11px">출처: <a href="'+SOURCE.url+'" target="_blank" rel="noopener noreferrer" style="color:#f472b6">'+SOURCE.title+'</a> · '+SOURCE.author+' · '+SOURCE.license+' · 14 templates</div>';}
  function createModal(){let modal=document.getElementById('reactorPromptModal');if(modal)return modal;modal=document.createElement('div');modal.id='reactorPromptModal';modal.className='reactor-modal';modal.addEventListener('click',function(e){if(e.target===modal)closeBuilder();});document.body.appendChild(modal);document.addEventListener('keydown',function(e){if(e.key==='Escape'&&modal.classList.contains('open'))closeBuilder();});return modal;}
  function openBuilder(id){const t=find(id);if(!t)return;builder=t;values={};const modal=createModal();modal.innerHTML='<div class="reactor-dialog"><div class="reactor-dialog-head"><div><div class="reactor-dialog-title">'+esc(t.title)+'</div><div class="reactor-credit">Reactor 원문 템플릿 · 변수 '+t.variables.length+'개</div></div><button class="reactor-dialog-close" onclick="reactorCloseBuilder()">×</button></div><div class="reactor-dialog-body"><div><div class="reactor-credit" style="margin-bottom:5px">원문 템플릿</div><pre class="reactor-original">'+esc(t.template)+'</pre></div><div class="reactor-fields">'+t.variables.map(function(v){return'<div class="reactor-field"><label>{'+esc(v)+'}</label><input data-reactor-variable="'+esc(v)+'" placeholder="'+esc(v.replace(/_/g,' ').toLowerCase())+'" oninput="reactorUpdateBuilder()"></div>';}).join('')+'</div><div><div class="reactor-credit" style="margin-bottom:5px">생성된 프롬프트</div><pre id="reactorBuilderResult" class="reactor-result">'+esc(t.template)+'</pre></div><div class="reactor-dialog-actions"><button class="reactor-dialog-primary" onclick="reactorApplyBuilder()">완성 프롬프트 적용</button><button class="reactor-dialog-secondary" onclick="reactorApplyExample()">공개 예시 즉시 적용</button><button class="reactor-dialog-secondary" onclick="reactorCopyOriginal()">원문 복사</button></div><div class="reactor-credit">원문 출처와 라이선스 표기는 Instagram 매니페스트에 함께 기록됩니다.</div></div></div>';modal.classList.add('open');}
  function builderResult(){if(!builder)return'';let result=builder.template;builder.variables.forEach(function(key){const value=values[key]||'{'+key+'}';result=result.split('{'+key+'}').join(value);});return result;}
  function updateBuilder(){if(!builder)return;document.querySelectorAll('[data-reactor-variable]').forEach(function(input){values[input.dataset.reactorVariable]=input.value.trim();});const out=document.getElementById('reactorBuilderResult');if(out)out.textContent=builderResult();}
  function applyBuilder(){updateBuilder();const missing=builder.variables.filter(function(k){return!values[k];});if(missing.length){alert('모든 변수를 입력하세요: '+missing.join(', '));return;}apply(builder.id,builderResult());closeBuilder();}
  function applyExample(){if(!builder)return;apply(builder.id,builder.example);closeBuilder();}
  function copyOriginal(){if(!builder)return;navigator.clipboard.writeText(builder.template).catch(function(){});}
  function closeBuilder(){const modal=document.getElementById('reactorPromptModal');if(modal)modal.classList.remove('open');builder=null;values={};}
  function generationMeta(){const t=selectedFromPrompt();return t?{id:t.id,title:t.title,category:t.category,allowIllustration:!!t.allowIllustration,allowPanel:!!t.allowPanel,allowText:!!t.allowText,source:SOURCE}:null;}

  window.REACTOR_PROMPT_TEMPLATES=TEMPLATES;
  window.REACTOR_PROMPT_SOURCE=SOURCE;
  window.reactorFilterPrompts=function(v){category=v;render();};
  window.reactorSearchPrompts=function(v){query=v;render();const el=document.getElementById('reactorPromptSearch');if(el){el.focus();el.setSelectionRange(el.value.length,el.value.length);}};
  window.reactorApplyPrompt=function(id){const t=find(id);if(t)apply(id,t.example);};
  window.reactorClearPromptStyle=clearSelection;
  window.reactorOpenBuilder=openBuilder;
  window.reactorCloseBuilder=closeBuilder;
  window.reactorUpdateBuilder=updateBuilder;
  window.reactorApplyBuilder=applyBuilder;
  window.reactorApplyExample=applyExample;
  window.reactorCopyOriginal=copyOriginal;
  window.reactorPromptGenerationMeta=generationMeta;
  window.reactorRenderPromptLibrary=render;
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
})();
