const assert = require('node:assert/strict');
const {compile,recommend} = require('../prompt-engine.js');
const catalog = require('../cinematography-catalog.json');
const shot = {id:'S1',description:'두 사람이 대치한다',initialState:'복도 양쪽에 서 있다',endState:'서로 바라보며 손을 멈춘다',duration:7};
const input = {projectKey:'test-A',model:'h3',shots:[shot]};
assert.equal(catalog.length,41);
assert.equal(new Set(catalog.map(c=>c.id)).size,41);
assert.equal(recommend(shot,catalog).framing.id,'two-shot');
assert.equal(recommend({...shot,description:'골목을 달려 추격한다',initialState:'골목 입구',endState:'문 앞에 선다'},catalog).movement.id,'tracking-shot');
assert.equal(recommend({...shot,framing:'overhead-shot',movement:'pan-shot'},catalog).framing.manual,true);
assert.throws(()=>recommend({...shot,movement:'close-up'},catalog),/촬영 기법/);

const h3 = compile({...input,shots:[{...shot,speaker:'민수',dialogue:'문을 열지 마.',voiceover:true},{...shot,id:'S2',duration:5,speaker:'민수',dialogue:'기다려.'}]},catalog);
assert.ok(h3.prompt.includes('[Shot 2] At 00:07.000'));
assert.ok(!h3.prompt.includes('[Shot 1] At'));
assert.ok(h3.prompt.includes('<d>[Korean] 문을 열지 마.</d>'));
assert.ok(h3.prompt.includes('lips remain completely closed'));
assert.ok(h3.prompt.includes('(S1) says: <d>[Korean] 기다려.</d>'));
assert.ok(!h3.fields.overall_soundscape.includes('문을 열지 마.'));
assert.ok(h3.fields.non_diegetic_music.startsWith('No non-diegetic score'));
assert.ok(!/cinematic|film still/i.test(h3.prompt));
assert.equal(h3.generationExecuted,false);

const seed = compile({...input,model:'seedance',shots:[{...shot,speaker:'민수',dialogue:'문을 열지 마.'},{...shot,id:'S2',duration:15}],references:[{type:'image',index:1,role:'민수의 얼굴',exclude:'배경과 의상',usedBy:['S1'],b64:'secret-image',token:'secret-token'}]},catalog);
assert.match(seed.prompt,/\[Stage 2\]/);
assert.ok(seed.prompt.includes('{문을 열지 마.}'));
assert.ok(seed.prompt.includes('@Image 1 defines 민수의 얼굴'));
assert.ok(!seed.prompt.split('[Stage 2]')[1].includes('Use: @Image 1'));
assert.ok(!JSON.stringify(seed).includes('secret-'));
assert.equal(seed.projectKey,'test-A');
assert.notEqual(seed.id,h3.id);
assert.throws(()=>compile({...input,shots:[{...shot,duration:16}]},catalog),/5–15/);
assert.throws(()=>compile({...input,shots:[{...shot,endState:''}]},catalog),/종료 상태/);
assert.throws(()=>compile({...input,shots:[{...shot,dialogue:'안녕'}]},catalog),/화자/);
assert.throws(()=>compile({...input,references:[{type:'image',index:1,role:'얼굴',exclude:''}]},catalog),/역할/);
assert.throws(()=>compile({...input,references:[{type:'audio',index:1,role:'목소리',exclude:'음악'}]},catalog),/단독/);
assert.throws(()=>compile({...input,references:[{type:'image',index:1,role:'얼굴',exclude:'배경',url:'https://example.com/img?token=secret'}]},catalog),/서명/);
assert.throws(()=>compile({...input,shots:[shot,shot]},catalog),/중복/);
console.log('prompt-engine: recommendation, model grammar, reference roles, limits and handoff checks PASS');
